name: Sync Back-end to Hugging Face
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true # Вмикаємо підтримку LFS для завантаження файлів з GitHub

      - name: Push Back-end subdirectory to Hugging Face Root
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Налаштування користувача Git
          git config --global user.email "gamlinskijoleg@example.com"
          git config --global user.name "gamlinskijoleg"

          # 2. Ініціалізація та налаштування Git LFS всередині раннера
          git lfs install
          git lfs track "*.pt"
          git lfs track "*.pth"

          # 3. Додаємо Hugging Face як remote
          git remote add hf https://gamlinskijoleg:$HF_TOKEN@huggingface.co/spaces/gamlinskijoleg/Easyroad

          # 4. Створюємо тимчасову гілку з вмістом папки back-end
          git subtree split --prefix back-end -b deploy-branch

          # 5. Перемикаємось на тимчасову гілку, щоб переконатися, що LFS підхопить атрибути
          git checkout deploy-branch

          # 6. Робимо ЖОРСТКИЙ пуш з увімкненим LFS на Hugging Face
          git push hf deploy-branch:main --force